print('Comparação (igual) 5 == 5: ', 5 == 5)
print("'Vin' == 'vin'", 'Vin' == 'vin')
print('Comparação (diferente) 3 != 5: ', 3 != 5)
print('Comparação (maior) 3 > 5: ', 3 > 5)
print('Comparação (menor) 3 < 5: ', 3 < 5)
print('Comparação (maior ou igual) 5 >= 5: ', 5 >= 5)
print('Comparação (menor ou igual) 5 <= 5: ', 5 <= 5)